### ISSUE TITLE
No longer works in matchmaking due to -override_vpk restriction

### ISSUE THREAD

**Issue by Tea23** [victorvde/dota2_nohats#11]
Nohats is no longer functional in public matchmaking as Valve have disallowed the use of -override_vpk there.

Nohats is not enabled when -enable_addons is used instead; heroes continue to look shitty.

**Comment by victorvde** [comment]
You have to use [some way to get override_vpk back in matchmaking](https://www.reddit.com/r/Dota2Modding/comments/2uspog/psa_an_update_to_enable_addons_now_supports_sound/cobex2j).

When there is a good and safe way to do this I might include it with the mod. Until then you'll just have to make do and complain to Valve.
